-- 1. Create the Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  description TEXT,
  type TEXT NOT NULL,
  color TEXT NOT NULL,
  calories INTEGER DEFAULT 0,
  rating NUMERIC DEFAULT 0,
  quantity INTEGER DEFAULT 1,
  discount INTEGER DEFAULT 0,
  image TEXT,
  raw_reviews JSONB DEFAULT '[]'::jsonb
);

-- 2. Insert Default Burger Menu Data
INSERT INTO products (name, price, description, type, color, calories, rating, quantity, discount, image, raw_reviews) VALUES
('Classic Chessy Burger', 15.99, 'A timeless classic with 100% Angus beef, fresh lettuce, tomato, and our secret sauce.', 'burger', '#ff9f1c', 850, 4.9, 100, 0, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80', '[{"id": 111, "userId": "u1", "userName": "Alice Freeman", "rating": 5, "comment": "Best burger I have ever had! The buns are so soft 🍔", "date": "2023-10-20T10:00:00Z"}]'::jsonb),
('Truffle Mushroom Swiss', 18.99, 'Earthy mushroom flavor combined with melting Swiss cheese and truffle aioli.', 'burger', '#2ec4b6', 850, 4.8, 100, 15, 'https://images.unsplash.com/photo-1594212202875-862ad35cb8ad?auto=format&fit=crop&q=80', '[]'::jsonb),
('Spicy Jalapeno Crunch', 16.99, 'For those who love heat. Packed with fresh jalapenos, pepper jack cheese, and spicy mayo.', 'burger', '#e71d36', 850, 4.8, 100, 0, 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&q=80', '[]'::jsonb),
('Double Smash Burger', 21.99, 'Two perfectly smashed patties with crispy edges, double cheese, and caramelized onions.', 'burger', '#ff6b6b', 850, 4.8, 100, 0, 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&q=80', '[]'::jsonb),
('BBQ Bacon Cowboy', 19.99, 'Thick-cut bacon, crispy onion rings, cheddar cheese, and house-made BBQ sauce.', 'burger', '#4cc9f0', 850, 4.8, 100, 10, 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80', '[]'::jsonb),
('Vegan Beyond Classic', 17.99, '100% plant-based patty, vegan cheese, and eggless mayo on a dairy-free bun.', 'burger', '#7bdff2', 850, 4.8, 100, 0, 'https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&q=80', '[]'::jsonb);

-- 3. Insert Bakery Data
INSERT INTO products (name, price, description, type, color, calories, rating, quantity, discount, image, raw_reviews) VALUES
('Artisan Sourdough Loaf', 8.99, 'Freshly baked sourdough with a crispy crust and chewy airy inside.', 'bakery', '#f9c22e', 320, 4.5, 100, 0, 'https://images.unsplash.com/photo-1585478259715-876a6a81fa08?auto=format&fit=crop&q=80', '[]'::jsonb),
('French Butter Croissant', 4.50, 'Flaky, buttery pastry baked to golden perfection everyday.', 'bakery', '#f4a261', 320, 4.5, 100, 0, 'https://images.unsplash.com/photo-1555507036-ab1e4006aa0a?auto=format&fit=crop&q=80', '[]'::jsonb),
('Pain au Chocolat', 5.50, 'Classic French pastry filled with rich dark chocolate batons.', 'bakery', '#e76f51', 320, 4.5, 100, 20, 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&q=80', '[]'::jsonb),
('Roasted Garlic Focaccia', 7.99, 'Italian flatbread infused with olive oil, rosemary, and roasted garlic.', 'bakery', '#2a9d8f', 320, 4.5, 100, 0, 'https://images.unsplash.com/photo-1598373182133-52452f7691ef?auto=format&fit=crop&q=80', '[]'::jsonb),
('Cinnamon Raisin Bagel', 3.99, 'Dense and chewy NYC-style bagel with warm cinnamon and sweet raisins.', 'bakery', '#e9c46a', 320, 4.5, 100, 0, 'https://images.unsplash.com/photo-1585478259715-876a6a81fa08?auto=format&fit=crop&q=80', '[]'::jsonb),
('Jalapeno Cheddar Bread', 9.99, 'Spicy jalapenos and sharp cheddar cheese baked right into the dough.', 'bakery', '#e71d36', 320, 4.5, 100, 0, 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80', '[]'::jsonb);

-- 4. Insert Cakes Data
INSERT INTO products (name, price, description, type, color, calories, rating, quantity, discount, image, raw_reviews) VALUES
('Red Velvet Dream', 45.00, 'Classic red velvet cake with rich cream cheese frosting.', 'cake', '#e63946', 540, 4.9, 100, 0, 'https://images.unsplash.com/photo-1586788224331-9a4f4ef11322?auto=format&fit=crop&q=80', '[]'::jsonb),
('Chocolate Fudge Truffle', 55.00, 'Decadent, dense chocolate cake layered with dark chocolate ganache.', 'cake', '#4a4e69', 540, 4.9, 100, 0, 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80', '[]'::jsonb),
('Vanilla Bean Strawberry', 48.00, 'Light vanilla sponge layered with fresh strawberries and whipped cream.', 'cake', '#f1faee', 540, 4.9, 100, 0, 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&q=80', '[]'::jsonb),
('Lemon Blueberry Burst', 42.00, 'Zesty lemon cake loaded with fresh blueberries and lemon butter.', 'cake', '#ffb703', 540, 4.9, 100, 0, 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&q=80', '[]'::jsonb);

-- 5. Insert Biscuit Data
INSERT INTO products (name, price, description, type, color, calories, rating, quantity, discount, image, raw_reviews) VALUES
('Classic Chocolate Chip', 12.99, 'Box of 12 soft-baked classic cookies loaded with chocolate chips.', 'biscuit', '#bc6c25', 200, 4.7, 100, 0, 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&q=80', '[]'::jsonb),
('Assorted Macarons', 24.99, 'Box of 6 colorful French macarons in seasonal flavors.', 'biscuit', '#fdfcdc', 200, 4.7, 100, 0, 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&q=80', '[]'::jsonb),
('Oatmeal Raisin Spice', 11.99, 'Box of 12 hearty oatmeal cookies with warm spices.', 'biscuit', '#dda15e', 200, 4.7, 100, 0, 'https://images.unsplash.com/photo-1558961363-a0c6489370bb?auto=format&fit=crop&q=80', '[]'::jsonb);

-- 6. Insert Sweet Data
INSERT INTO products (name, price, description, type, color, calories, rating, quantity, discount, image, raw_reviews) VALUES
('Pistachio Baklava', 15.00, 'Flaky filo pastry layered with honey and crushed pistachios.', 'sweet', '#a7c957', 150, 4.6, 100, 0, 'https://images.unsplash.com/photo-1519706316710-d8cd59a0f4db?auto=format&fit=crop&q=80', '[]'::jsonb),
('Classic Tiramisu', 8.50, 'Italian dessert made of ladyfingers dipped in coffee, layered with mascarpone.', 'sweet', '#9c6644', 150, 4.6, 100, 0, 'https://images.unsplash.com/photo-1571115177098-24db0de28987?auto=format&fit=crop&q=80', '[]'::jsonb),
('New York Cheesecake', 7.50, 'Dense, rich, and creamy genuine New York style cheesecake slice.', 'sweet', '#ffe8d6', 150, 4.6, 100, 0, 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80', '[]'::jsonb);

-- 7. Fix Permissions automatically
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone."
  ON products FOR SELECT
  USING ( true );

CREATE POLICY "Users can insert their own profile."
  ON products FOR INSERT
  WITH CHECK ( true );

CREATE POLICY "Users can update own profile."
  ON products FOR UPDATE
  USING ( true );

CREATE POLICY "Users can delete own profile."
  ON products FOR DELETE
  USING ( true );
